version: '2'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - '3000'
      - '8080'
    ports:
      - '3000:3000'
      - '8080:80'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
